FROM ubuntu:18.04
RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y \
        cmake \
        coreutils \
        libcunit1-dev \
        exuberant-ctags \
        libfftw3-dev \
        libomp-dev \
        libzstd1-dev \
        libnetcdf-dev \
        ocl-icd-opencl-dev \
        opencl-clhpp-headers \
        gcc \
        g++ \
        zlib1g-dev && \
    apt-get clean all
COPY . /build/
WORKDIR /build/
RUN rm -rf build && \
    mkdir -p build && \
    cd build && \
    cmake .. && \
    make -j $(nproc --all)
